### PR TITLE
updated ui issues and bug fixes

### PR DESCRIPTION
**Pull request by Gveetil**

### CODE REVIEW

**Review by atulsd — COMMENTED** [review]
All good

**Review by atulsd — COMMENTED** [review]
All good

**Comment by alibahrami633** [comment]
...

**Review by alibahrami633 — APPROVED** [review]

**Review by alibahrami633 — APPROVED** [review]

**Comment by alibahrami633** [comment]
.

**Review by alibahrami633 — APPROVED** [review]
.

**Pull request merged**
